rules:
  - host: "mc.website1.com"
    tag: "irl"
    message: 'tellraw %player% ["Server status, Discord link, and live map view:\n",{"text":"website1.com/mc","clickEvent":{"action":"open_url","value":"https://website1.com/mc"},"color":"#77cc77"}]'
  - host: "mc.website2.com"
    tag: ""
    message: 'tellraw %player% ["Server status, Discord link, and live map view:\n",{"text":"website2.com/mc","clickEvent":{"action":"open_url","value":"https://website2.com/mc"},"color":"#2670B7"}]'

tag_name: "irl"
remove_on_unmapped: false
message_delay_ticks: 20   # ~1 second; increase if needed (e.g., 40 = 2s)