rules:
  - host: "mc.website1.com"
    tag: "team1"        # adds scoreboard tag "irl"
    message: 'tellraw %player% ["§aWelcome! See: ",{"text":"website1.com/mc","clickEvent":{"action":"open_url","value":"https://website1.com/mc"}}]'

  - host: "mc.website2.com"
    tag: "team2"     # adds scoreboard tag "friend"
    message: 'tellraw %player% ["§9Hey! Info: ",{"text":"website2.com/mc","clickEvent":{"action":"open_url","value":"https://website2.com/mc"}}]'

  - host: "mc.website3.com"
    tag: "web3"        # adds scoreboard tag "dev"
    message: 'tellraw %player% ["§eWelcome to the website 3 server!"]'

  - host: "mc.website4.com"
    tag: "web4"  # adds scoreboard tag "community"
    message: 'tellraw %player% ["§dWelcome to the website 4 server!"]'

# Behavior switches
exclusive: true                 # keep only ONE of the known rule-tags at a time (recommended)
clear_all_known_on_unmapped: false  # if true, remove ALL known rule-tags when host is unmapped (IP, ISP rDNS, etc.)
message_delay_ticks: 20         # ~1s delay so tellraw hits after join